---
- name: check {{ cfg_path }} deposition
  stat:
    path: "{{ cfg_path }}"
  register: response
  failed_when: >
    not response.stat.exists
    or response.stat.pw_name != 'irods'
    or response.stat.gr_name != 'irods'

- name: validate {{ cfg_path }} with schema
  shell: jsonschema --instance '{{ cfg_path }}' '/var/lib/irods/{{ schema }}'
  changed_when: false