---
- when: _icat is mapping
  block:
    - name: database_config | validate params
      when: _validate | bool
      assert:
        that:
          - _icat.catalog_database_type in ('mysql', 'oracle', 'postgres')
          - _icat.db_port | int >= 1 and _icat.db_port | int <= 65535

    - include_tasks: _cfg_template.yml
      vars:
        _cfg_template_dest_file: etc/irods/database_config.json

- name: database_config | ensure known that changes were made
  meta: flush_handlers
