---
- name: validate address type for hosts_config
  when: _validate | bool
  with_items: "{{ _host_entries }}"
  assert:
    that:
      - item.address_type == 'local' or item.address_type == 'remote'
  failed_when: false

- include_tasks: _cfg_template.yml
  vars:
    _cfg_template_dest_file: etc/irods/hosts_config.json

- name: ensure known that changes were made
  meta: flush_handlers
