---
- name: verify | irods_environment.json generation
  hosts: all
  gather_facts: false
  tasks:
    - name: test ensure /var/lib/irods/deposit exists
      stat:
        path: /var/lib/irods/deposit
      register: response
      failed_when: >
        not response.stat.exists or
        response.stat.pw_name != 'irods' or
        response.stat.gr_name != 'irods'

    - name: test generate irods_environment.json
      stat:
        path: /var/lib/irods/deposit/irods_environment.json
      register: response
      failed_when: >
        not response.stat.exists or
        response.stat.pw_name != 'irods' or
        response.stat.gr_name != 'irods'


- name: verify | client configuration file placement
  hosts: all
  gather_facts: false
  tasks:
    - name: check irods_environment.json deposition
      stat:
        path: /home/irods/.irods/irods_environment.json
      register: response
      failed_when: >
        not response.stat.exists
        or response.stat.pw_name != 'irods'
        or response.stat.gr_name != 'irods'

    - name: check ie.json deposition
      stat:
        path: /tmp/ie.json
      register: response
      failed_when: >
        not response.stat.exists
        or response.stat.pw_name == 'irods'
        or response.stat.gr_name == 'irods'
