---
- name: converge
  hosts: all
  collections:
    - ansible.builtin
  tasks:
    - name: do not give file irods ownership
      include_role:
        name: ansible-irods-cfg
        tasks_from: _system_account_own.yml
      vars:
        irods_cfg_chown: false
        _system_account_own_path: /etc/irods/not_owner_test

    - name: give file irods ownershop
      include_role:
        name: ansible-irods-cfg
        tasks_from: _system_account_own.yml
      vars:
        irods_cfg_chown: true
        _system_account_own_path: /etc/irods/owner_test