---
- import_playbook: ../_shared/prepare.yml


- name: prepare
  hosts: all
  gather_facts: false
  collections:
    - ansible.builtin
  tasks:
    - name: create config directory
      file:
        path: /etc/irods
        state: directory
        owner: irods

    - name: create file to not receive ownership
      file:
        path: /etc/irods/not_owner_test
        state: touch

    - name: create file to receive ownership
      file:
        path: /etc/irods/owner_test
        state: touch