---
- name: prepare
  hosts: all
  collections:
    - ansible.builtin
  tasks:
    - name: create irods user
      user:
        name: irods
        home: /var/lib/irods

    - name: create config directory
      file:
        path: /etc/irods
        state: directory
        owner: irods

    - name: create file to not receive ownership
      file:
        path: /etc/irods/not_owner_test
        state: touch

    - name: create file to receive ownership
      file:
        path: /etc/irods/owner_test
        state: touch