---
dependency:
  name: galaxy
  options:
    role-file: molecule/_shared/requirements.yml
    requirements-file: molecule/_shared/requirements.yml
driver:
  name: docker
platforms:
  - name: centos
    image: centos:7
  - name: ubuntu
    image: ubuntu:bionic
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        irods_cfg_validate: true
verifier:
  name: ansible