---
name: Molecule Test
on: [ push, pull_request, workflow_dispatch ]
jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          path: "${{ github.repository }}"
 
      - uses: gofrolist/molecule-action@v2
        with:
          molecule_command: test
          molecule_args: --all
          